Testing release cut
Signed-off-by: Abrie van Aardt <vanaardta@bbd.co.za>

diff --git a/azure/release-pipeline.yml b/azure/release-pipeline.yml
--- a/azure/release-pipeline.yml
+++ b/azure/release-pipeline.yml
@@ -2,6 +2,7 @@ trigger:
   branches:
     include:
       - 'refs/tags/*'
+pr: none
 jobs:
 - job: publish_release
   displayName: Build and Publish Release
@@ -13,17 +14,34 @@ jobs:
   steps:
   - checkout: self
     persistCredentials: true
+    clean: true
   - template: templates/maven.yml
   - template: templates/analyse.yml
   - bash: |
       extracted_version=$(echo "$BUILD_SOURCEBRANCH" | rev | cut -d/ -f1 | rev)
       echo "##vso[task.setvariable variable=project_version]$extracted_version"
+      echo "Git tag version: $extracted_version"
     displayName: 'Extract version from Git tag'
     failOnStderr: true  
+  - bash: |
+      echo "Validating format of tagged version..."
+      echo "$PROJECT_VERSION" | grep -P "^[1-9]\d*?\.\d+?.\d+?$"
+      if [ $? -ne 0 ]; then
+        echo "Invalid version $PROJECT_VERSION - Please supply a tag in major.minor.patch format (1.0.0 at the least)."
+        exit 1
+      fi
+      echo "Version passed validation."
+    displayName: 'Validate tagged version'
+    failOnStderr: true
   - template: templates/download-secure-files.yml
   - template: templates/maven.yml
     parameters:
-      displayName: 'Maven deploy release version'
+      displayName: 'Maven create release version'
       goals: | 
-        --settings=$(mavenSettings.secureFilePath) -Pcreate-release-version,release-oss-maven-central  -DreleaseVersion=$(project_version)-RELEASE -Dgpg.publicKeyring=$(publicKeyRing.secureFilePath) -Dgpg.secretKeyring=$(privateKeyRing.secureFilePath) deploy
-  # 4. Create github release
+        -Pcreate-release-version  -DreleaseVersion=$(project_version) validate
+  - template: templates/maven.yml
+    parameters:
+      displayName: 'Maven publish release version'
+      goals: |
+        --settings=$(mavenSettings.secureFilePath) -Prelease-oss-maven-central -Dgpg.publicKeyring=$(publicKeyRing.secureFilePath) -Dgpg.secretKeyring=$(privateKeyRing.secureFilePath) deploy
+  # TODO: Create github release here
